#!/bin/sh

if git diff --cached --name-only -- '*.json' | grep -q 'wordPairs'; then
  echo "Running validate-wordpairs because JSON changed..."
  npm run validate-wordpairs
else
  echo "No wordPairs JSON changes, skipping validate-wordpairs."
fi

npx lint-staged